name: Build Image

on:
  pull_request:

env:
  IMAGE: ghcr.io/zeitonline/pre-commit-image
  # https://github.com/orgs/community/discussions/26676#discussioncomment-3252813
  COMMIT_SHA: ${{github.event.pull_request.head.sha}}

jobs:
  build:
    name: Build
    runs-on: [self-hosted, x64, linux, ephemeral, zon-image-latest]
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - run: docker context create buildx
    - uses: docker/setup-buildx-action@v2
      with:
        endpoint: buildx  # created in previous step
        driver-opts: network=host

    # XXX You have to (once) manually change the package visibility to public at
    # https://github.com/orgs/ZeitOnline/packages/container/pre-commit-image/settings
    # otherwise GHA cannot use it in jobs.*.container, see
    # https://niklasmtj.de/blog/gh-actions-workflows-combination-with-ghcr
    - uses: docker/build-push-action@v4
      with:
        context: .
        tags: ${{env.IMAGE}}:${{env.COMMIT_SHA}}
        pull: true
        push: true
